// Generated by Xata Codegen 0.21.0. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "profiles",
    columns: [
      { name: "username", type: "string", unique: true },
      {
        name: "name",
        type: "string",
        notNull: true,
        defaultValue: "Anthony Cueva",
      },
      { name: "bio", type: "string" },
      { name: "birthdate", type: "datetime" },
      { name: "follower_count", type: "int", notNull: true, defaultValue: "0" },
      {
        name: "following_count",
        type: "int",
        notNull: true,
        defaultValue: "0",
      },
      { name: "image", type: "string" },
      { name: "like_count", type: "int", notNull: true, defaultValue: "0" },
      { name: "article_count", type: "int", notNull: true, defaultValue: "0" },
    ],
  },
  {
    name: "articles",
    columns: [
      { name: "hashtags", type: "multiple" },
      { name: "author", type: "link", link: { table: "profiles" } },
      {
        name: "body",
        type: "text",
        notNull: true,
        defaultValue: "# Hello world!",
      },
      { name: "like_count", type: "int", notNull: true, defaultValue: "0" },
      {
        name: "publication_date",
        type: "datetime",
        notNull: true,
        defaultValue: "2001-11-30T01:02:03.004Z",
      },
      { name: "star_count", type: "int", notNull: true, defaultValue: "0" },
      { name: "bookmark_count", type: "int", notNull: true, defaultValue: "0" },
      { name: "children_count", type: "int", notNull: true, defaultValue: "0" },
      { name: "comment_count", type: "int", notNull: true, defaultValue: "0" },
      { name: "parent", type: "link", link: { table: "articles" } },
      {
        name: "is_question",
        type: "bool",
        notNull: true,
        defaultValue: "false",
      },
    ],
  },
  {
    name: "profile_article_rels",
    columns: [
      { name: "article", type: "link", link: { table: "articles" } },
      { name: "like_status", type: "bool", defaultValue: "false" },
      { name: "profile", type: "link", link: { table: "profiles" } },
      { name: "comment_count", type: "int", notNull: true, defaultValue: "0" },
      { name: "children_count", type: "int", notNull: true, defaultValue: "0" },
      { name: "star_count", type: "int", notNull: true, defaultValue: "0" },
    ],
  },
  {
    name: "accounts",
    columns: [
      { name: "type", type: "string" },
      { name: "provider", type: "string" },
      { name: "access_token", type: "string" },
      { name: "token_type", type: "string" },
      { name: "scope", type: "string" },
      { name: "id_token", type: "string" },
      { name: "session_state", type: "string" },
      { name: "oauth_token_secret", type: "string" },
      { name: "oauth_token", type: "string" },
      { name: "user", type: "link", link: { table: "users" } },
      { name: "providerAccountId", type: "string", unique: true },
      { name: "refresh_token", type: "string" },
      { name: "expires_at", type: "int" },
      { name: "userId", type: "string" },
    ],
  },
  {
    name: "comments",
    columns: [
      { name: "like_count", type: "int", notNull: true, defaultValue: "0" },
      { name: "body", type: "string", notNull: true, defaultValue: "sasd" },
      {
        name: "publication_date",
        type: "datetime",
        notNull: true,
        defaultValue: "2022-11-17T00:00:00Z",
      },
      { name: "author", type: "link", link: { table: "profiles" } },
      { name: "article", type: "link", link: { table: "articles" } },
    ],
  },
  {
    name: "profile_rels",
    columns: [
      { name: "follower", type: "link", link: { table: "profiles" } },
      { name: "followee", type: "link", link: { table: "profiles" } },
      {
        name: "creation_date",
        type: "datetime",
        notNull: true,
        defaultValue: "2022-12-20T01:11:01.001Z",
      },
      { name: "following_status", type: "bool" },
    ],
  },
  {
    name: "sponsor_question_rels",
    columns: [
      { name: "sponsor", type: "link", link: { table: "profiles" } },
      { name: "question", type: "link", link: { table: "articles" } },
      { name: "message", type: "string" },
    ],
  },
  {
    name: "users",
    columns: [
      { name: "email", type: "email", unique: true },
      {
        name: "profile",
        type: "link",
        link: { table: "profiles" },
        unique: true,
      },
      { name: "blocked_status", type: "bool", defaultValue: "false" },
      { name: "emailVerified", type: "datetime" },
    ],
  },
  {
    name: "sessions",
    columns: [
      { name: "user", type: "link", link: { table: "users" } },
      { name: "expires", type: "datetime" },
      { name: "sessionToken", type: "string" },
      { name: "userId", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Profiles = InferredTypes["profiles"];
export type ProfilesRecord = Profiles & XataRecord;

export type Articles = InferredTypes["articles"];
export type ArticlesRecord = Articles & XataRecord;

export type ProfileArticleRels = InferredTypes["profile_article_rels"];
export type ProfileArticleRelsRecord = ProfileArticleRels & XataRecord;

export type Accounts = InferredTypes["accounts"];
export type AccountsRecord = Accounts & XataRecord;

export type Comments = InferredTypes["comments"];
export type CommentsRecord = Comments & XataRecord;

export type ProfileRels = InferredTypes["profile_rels"];
export type ProfileRelsRecord = ProfileRels & XataRecord;

export type SponsorQuestionRels = InferredTypes["sponsor_question_rels"];
export type SponsorQuestionRelsRecord = SponsorQuestionRels & XataRecord;

export type Users = InferredTypes["users"];
export type UsersRecord = Users & XataRecord;

export type Sessions = InferredTypes["sessions"];
export type SessionsRecord = Sessions & XataRecord;

export type DatabaseSchema = {
  profiles: ProfilesRecord;
  articles: ArticlesRecord;
  profile_article_rels: ProfileArticleRelsRecord;
  accounts: AccountsRecord;
  comments: CommentsRecord;
  profile_rels: ProfileRelsRecord;
  sponsor_question_rels: SponsorQuestionRelsRecord;
  users: UsersRecord;
  sessions: SessionsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://anthony-cueva-s-workspace-iae285.us-east-1.xata.sh/db/apprendamos",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
